name: Create a comment on new issues

on:
   issues:
     types: [opened]

jobs:
  commment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
               This is a multi-line test comment
               - With GitHub **Markdown** :sparkles:
               - Created by [create-or-update-comment][1]

                [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: '+1'
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        run: |
           gh api -X post \
              http://api.github.com/repo/${ORGANIZATION/${PEPOSITORY}/issues/${ISSUE_NUMBER/comments /
              -f body='
               commment but from the API call not action
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB.TOKEN }}
            ORGANZATION: ${{ github.event.organsation.login }}
            REPOSITORY: ${{ github.event.repository.name }}
            ISSUE_NUMBER: ${{ github.event.issue.number }}
            

               
