name: Create a comment on new issues
on:
   issues:
      types: [opened]

jobs:
 commment-with-action:
    runs-on: ubuntu-latest
    steps:
        - name: "dump github context"
          run: echo "${{ tojson(github.evnet) }}" | jq
          shell: bash
  
